spring:
  datasource:
    url: jdbc:mysql://mysql1:3306/mydb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    url: jdbc:mysql://167.179.109.92:3306/mydb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    url: jdbc:mysql://localhost:3306?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema:
      - classpath:schema.sql
    initialization-mode: always
server:
  port: 8080